// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: contracts/api.proto

package contracts

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Explorer_Ls_FullMethodName = "/Explorer/Ls"
)

// ExplorerClient is the client API for Explorer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExplorerClient interface {
	Ls(ctx context.Context, in *LsRequest, opts ...grpc.CallOption) (*LsResponse, error)
}

type explorerClient struct {
	cc grpc.ClientConnInterface
}

func NewExplorerClient(cc grpc.ClientConnInterface) ExplorerClient {
	return &explorerClient{cc}
}

func (c *explorerClient) Ls(ctx context.Context, in *LsRequest, opts ...grpc.CallOption) (*LsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LsResponse)
	err := c.cc.Invoke(ctx, Explorer_Ls_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExplorerServer is the server API for Explorer service.
// All implementations must embed UnimplementedExplorerServer
// for forward compatibility.
type ExplorerServer interface {
	Ls(context.Context, *LsRequest) (*LsResponse, error)
	mustEmbedUnimplementedExplorerServer()
}

// UnimplementedExplorerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExplorerServer struct{}

func (UnimplementedExplorerServer) Ls(context.Context, *LsRequest) (*LsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ls not implemented")
}
func (UnimplementedExplorerServer) mustEmbedUnimplementedExplorerServer() {}
func (UnimplementedExplorerServer) testEmbeddedByValue()                  {}

// UnsafeExplorerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExplorerServer will
// result in compilation errors.
type UnsafeExplorerServer interface {
	mustEmbedUnimplementedExplorerServer()
}

func RegisterExplorerServer(s grpc.ServiceRegistrar, srv ExplorerServer) {
	// If the following call pancis, it indicates UnimplementedExplorerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Explorer_ServiceDesc, srv)
}

func _Explorer_Ls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExplorerServer).Ls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Explorer_Ls_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExplorerServer).Ls(ctx, req.(*LsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Explorer_ServiceDesc is the grpc.ServiceDesc for Explorer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Explorer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Explorer",
	HandlerType: (*ExplorerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ls",
			Handler:    _Explorer_Ls_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contracts/api.proto",
}
