// @generated by protobuf-ts 2.9.4 with parameter optimize_code_size
// @generated from protobuf file "contracts/api.proto" (syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../google/protobuf/timestamp";
/**
 * @generated from protobuf message File
 */
export interface File {
    /**
     * @generated from protobuf field: File.FileType file_type = 1;
     */
    fileType: File_FileType;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: string path = 3;
     */
    path: string;
    /**
     * @generated from protobuf field: int32 size = 4;
     */
    size: number;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 5;
     */
    createdAt?: Timestamp;
}
/**
 * @generated from protobuf enum File.FileType
 */
export enum File_FileType {
    /**
     * @generated from protobuf enum value: FILE_TYPE_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: FILE_TYPE_FILE = 1;
     */
    FILE = 1,
    /**
     * @generated from protobuf enum value: FILE_TYPE_DIR = 2;
     */
    DIR = 2
}
/**
 * @generated from protobuf message LsRequest
 */
export interface LsRequest {
    /**
     * @generated from protobuf field: string location = 1;
     */
    location: string;
}
/**
 * @generated from protobuf message LsResponse
 */
export interface LsResponse {
    /**
     * @generated from protobuf field: string location = 1;
     */
    location: string;
    /**
     * @generated from protobuf field: repeated File files = 2;
     */
    files: File[];
}
// @generated message type with reflection information, may provide speed optimized methods
class File$Type extends MessageType<File> {
    constructor() {
        super("File", [
            { no: 1, name: "file_type", kind: "enum", T: () => ["File.FileType", File_FileType, "FILE_TYPE_"] },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "path", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "size", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "created_at", kind: "message", T: () => Timestamp }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message File
 */
export const File = new File$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LsRequest$Type extends MessageType<LsRequest> {
    constructor() {
        super("LsRequest", [
            { no: 1, name: "location", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message LsRequest
 */
export const LsRequest = new LsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LsResponse$Type extends MessageType<LsResponse> {
    constructor() {
        super("LsResponse", [
            { no: 1, name: "location", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "files", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => File }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message LsResponse
 */
export const LsResponse = new LsResponse$Type();
/**
 * @generated ServiceType for protobuf service Explorer
 */
export const Explorer = new ServiceType("Explorer", [
    { name: "Ls", options: {}, I: LsRequest, O: LsResponse }
]);
